stages:
  - build
  - test
  - publish

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:latest
  script:
    -  mvn --batch-mode --update-snapshots package
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  image: maven:latest
  script:
    - mvn -B test

docker build:
  stage: publish
  image: docker:20.10.13-alpine3.15
  script: 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"

